name: Build & Deploy FHIR IG

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make publisher scripts executable (no-op if already)
        run: chmod +x _updatePublisher.sh _genonce.sh || true

      - name: Update the image to the latest publisher
        uses: docker://hl7fhir/ig-publisher-base:latest
        with:
          args: ./_updatePublisher.sh --force

      - name: Run SUSHI to generate the ig.ini file
        uses: docker://hl7fhir/ig-publisher-base:latest
        with:
          args: sushi

      - name: Run the IG Publisher
        uses: docker://hl7fhir/ig-publisher-base:latest
        with:
          args: ./_genonce.sh -no-sushi

      - name: Locate site root (find index.html under output)
        id: find_site
        run: |
          echo "PWD=$(pwd)"
          echo "Output tree (2 levels):"
          find output -maxdepth 2 -type f -print | sort | head -n 200 || true

          if [ -f output/index.html ]; then
            SITE_DIR="output"
          else
            FOUND="$(find output -type f -name index.html | head -n 1 || true)"
            if [ -n "$FOUND" ]; then
              SITE_DIR="$(dirname "$FOUND")"
            else
              echo "::error::No index.html found anywhere under output/"
              exit 1
            fi
          fi

          echo "Detected site directory: $SITE_DIR"
          echo "SITE_DIR=$SITE_DIR" >> "$GITHUB_ENV"

      - name: Disable Jekyll on the generated site
        run: touch "${{ env.SITE_DIR }}/.nojekyll"

      - name: Upload build output for PRs (debug/preview)
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: site-output-pr-${{ github.run_id }}
          path: ${{ env.SITE_DIR }}

      - name: Deploy to GitHub Pages (gh-pages branch)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.SITE_DIR }}
          enable_jekyll: false