# This is a basic workflow to help you get started with Actions

permissions:
  contents: write         # needed to push commits/tags
  pull-requests: write

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ Create-FHIR-IG ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Ensure scripts are present (optional if you committed them)
      - name: Fetch publisher scripts (if missing)
        run: |
          [ -f _updatePublisher.sh ] || curl -sSL https://raw.githubusercontent.com/HL7/ig-publisher-scripts/main/_updatePublisher.sh -o _updatePublisher.sh
          [ -f _genonce.sh ] || curl -sSL https://raw.githubusercontent.com/HL7/ig-publisher-scripts/main/_genonce.sh -o _genonce.sh
          chmod +x _updatePublisher.sh _genonce.sh

      - name: Update IG Publisher
        run: bash -euo pipefail _updatePublisher.sh -y

      # If you use FHIR Shorthand, run SUSHI first to generate ig.ini, etc.
      # - name: Run SUSHI
      #   run: npx -y fsh-sushi

      - name: Build IG (genonce)
        run: bash -euo pipefail _genonce.sh

      - name: Verify output exists
        run: test -f output/index.html || { echo "No IG output produced"; exit 1; }

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output