name: Build & Deploy FHIR IG

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update the image to the latest publisher
        uses: docker://hl7fhir/ig-publisher-base:latest
        with:
          args: ./_updatePublisher.sh --force

      - name: Run SUSHI to generate the ig.ini file
        uses: docker://hl7fhir/ig-publisher-base:latest
        with:
          args: sushi

      - name: Run the IG Publisher
        uses: docker://hl7fhir/ig-publisher-base:latest
        with:
          args: ./_genonce.sh -no-sushi

      - name: Deploy to GitHub Pages (gh-pages branch)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          enable_jekyll: false