name: Pages (PR previews)

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

permissions:
  contents: write
  pull-requests: write


jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Deploy PR preview into a subdir and comment the URL on the PR
      - name: Deploy PR preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: output             # your built static files
          preview-branch: gh-pages        # branch used for previews
          umbrella-dir: pr-preview        # previews live under /pr-preview/
          action: auto                    # deploy on open/sync, clean on close